import { CameraOutlined, CarOutlined, SafetyCertificateOutlined, SettingOutlined, TableOutlined, TagOutlined, ToolOutlined, VideoCameraOutlined, WarningOutlined } from '@ant-design/icons'

import { APP_PREFIX_PATH } from '@/configs/AppConfig'
import { NavItem } from '@/types/custom'

const navigationConfig: Array<NavItem> = [
	// {
	//     key: 'dashboard',
	//     path: `${APP_PREFIX_PATH}/dashboard`,
	//     title: 'Дэшборд',
	//     icon: DashboardOutlined,
	//     breadcrumb: true,
	//     role: ['superadmin', 'administrator'],
	// },
	// {
	// 	key: 'cameras',
	// 	path: `${APP_PREFIX_PATH}/cameras`,
	// 	title: 'Просмотр камер',
	// 	icon: VideoCameraOutlined,
	// 	breadcrumb: true,
	// 	role: ['superadmin', 'administrator', 'employee'],
	// },
	// {
	//     key: 'transport',
	//     path: `${APP_PREFIX_PATH}/transport`,
	//     title: 'Транспорт',
	//     icon: PicLeftOutlined,
	//     breadcrumb: true,
	//     role: ['superadmin', 'admin'],
	// },
	{
	    key: 'incidents',
	    path: `${APP_PREFIX_PATH}/incidents`,
	    title: 'Инциденты',
	    icon: WarningOutlined,
	    breadcrumb: true,
	    role: ['superadmin', 'administrator', 'employee'],
	},
	// {
	// 	key: 'repair_car',
	// 	path: `${APP_PREFIX_PATH}/repair_car`,
	// 	title: 'Обслуживание машин',
	// 	breadcrumb: true,
	// 	icon: CarOutlined,
	// 	role: ['superadmin', 'administrator'],
	// },
	// {
	//     key: 'documentation',
	//     path: null,
	//     title: 'Документация',
	//     icon: FileTextOutlined,
	//     breadcrumb: true,
	//     role: ['superadmin', 'administrator'],
	//     submenu: [
	//         {
	//             key: 'dailyOrders',
	//             path: `${APP_PREFIX_PATH}/daily-orders`,
	//             title: 'Суточные приказы',
	//             breadcrumb: true,
	//             role: ['superadmin', 'administrator'],
	//         },
	//         {
	//             key: 'waybills',
	//             path: `${APP_PREFIX_PATH}/waybills`,
	//             title: 'Путевые листы',
	//             breadcrumb: true,
	//             role: ['superadmin', 'administrator'],
	//         },
	//     ],
	// },
	// {
	// 	key: 'safety',
	// 	title: 'Безопасность',
	// 	path: '',
	// 	breadcrumb: true,
	// 	icon: SafetyCertificateOutlined,
	// 	role: ['superadmin', 'administrator'],
	// 	submenu: [
	// 		{
	// 			key: 'fire',
	// 			path: `${APP_PREFIX_PATH}/fire`,
	// 			title: 'Пожар',
	// 			breadcrumb: true,
	// 			role: ['superadmin', 'administrator'],
	// 		},
	// 		{
	// 			key: 'crowd',
	// 			path: `${APP_PREFIX_PATH}/crowd`,
	// 			title: 'Толпа',
	// 			breadcrumb: true,
	// 			role: ['superadmin', 'administrator'],
	// 		},
	// 		{
	// 			key: 'violence',
	// 			path: `${APP_PREFIX_PATH}/violence`,
	// 			title: 'Насилие',
	// 			breadcrumb: true,
	// 			role: ['superadmin', 'administrator'],
	// 		},
	// 		{
	// 			key: 'camera_block',
	// 			path: `${APP_PREFIX_PATH}/camera_block`,
	// 			title: 'Камера заблокирована',
	// 			breadcrumb: true,
	// 			role: ['superadmin', 'administrator'],
	// 		},
	// 		{
	// 			key: 'face_recognition_enter',
	// 			path: `${APP_PREFIX_PATH}/face_recognition_enter`,
	// 			title: 'FaceID',
	// 			breadcrumb: true,
	// 			role: ['superadmin', 'administrator'],
	// 		},
	// 		{
	// 			key: 'license_plate_recognition_enter',
	// 			path: `${APP_PREFIX_PATH}/license_plate_recognition_enter`,
	// 			title: 'PlateID',
	// 			breadcrumb: true,
	// 			role: ['superadmin', 'administrator'],
	// 		},
	// 	],
	// },
	// {
	// 	key: 'industry',
	// 	title: 'Промышленность',
	// 	path: '',
	// 	breadcrumb: true,
	// 	icon: ToolOutlined,
	// 	role: ['superadmin', 'administrator'],
	// 	submenu: [
	// 		{
	// 			key: 'thermo_zone',
	// 			path: `${APP_PREFIX_PATH}/thermo_zone`,
	// 			title: 'Мониторинг термокритичной зоны',
	// 			breadcrumb: true,
	// 			role: ['superadmin', 'administrator'],
	// 		},
	// 		{
	// 			key: 'working_hours',
	// 			path: `${APP_PREFIX_PATH}/working_hours`,
	// 			title: 'Учет рабочего времени мастеров по фрезеровки',
	// 			breadcrumb: true,
	// 			role: ['superadmin', 'administrator'],
	// 		},
	// 		{
	// 			key: 'storage',
	// 			path: `${APP_PREFIX_PATH}/storage`,
	// 			title: 'Мониторинг склада готовой продукции',
	// 			breadcrumb: true,
	// 			role: ['superadmin', 'administrator'],
	// 		},
	// 		{
	// 			key: 'acceptance',
	// 			path: `${APP_PREFIX_PATH}/acceptance`,
	// 			title: 'Мониторинг приемки сырья',
	// 			breadcrumb: true,
	// 			role: ['superadmin', 'administrator'],
	// 		},
	// 	],
	// },
	// {
	// 	key: 'commerce',
	// 	title: 'Коммерция',
	// 	path: '',
	// 	breadcrumb: true,
	// 	icon: TagOutlined,
	// 	role: ['superadmin', 'administrator'],
	// 	submenu: [
	// 		{
	// 			key: 'service_table',
	// 			path: `${APP_PREFIX_PATH}/service_table`,
	// 			title: 'Расчет времени обслуживания стола в ресторане',
	// 			breadcrumb: true,
	// 			role: ['superadmin', 'administrator'],
	// 		},
	// 		{
	// 			key: 'people_map',
	// 			path: `${APP_PREFIX_PATH}/people_map`,
	// 			title: 'Тепловая карта людей',
	// 			breadcrumb: true,
	// 			role: ['superadmin', 'administrator'],
	// 		},
	// 		{
	// 			key: 'cashier',
	// 			path: `${APP_PREFIX_PATH}/cashier`,
	// 			title: 'Учет кассира на кассе',
	// 			breadcrumb: true,
	// 			role: ['superadmin', 'administrator'],
	// 		},
	// 		{
	// 			key: 'checkout_lines',
	// 			path: `${APP_PREFIX_PATH}/checkout_lines`,
	// 			title: 'Учёт очереди на кассе',
	// 			breadcrumb: true,
	// 			role: ['superadmin', 'administrator'],
	// 		},
	// 	],
	// },
// 	{
// 		key: 'settings',
// 		path: `${APP_PREFIX_PATH}/settings`,
// 		title: 'Настройки',
// 		icon: SettingOutlined,
// 		breadcrumb: true,
// 		role: ['superadmin', 'administrator', 'employee'],
// 		submenu: [
// 				{
// 						key: 'checkpoint',
// 						path: `${APP_PREFIX_PATH}/checkpoint`,
// 						title: 'КПП',
// 						icon: CameraOutlined,
// 						breadcrumb: true,
// 						role: ['superadmin', 'administrator', 'employee'],
// 				},
// 				{
// 						key: 'attendance',
// 						path: `${APP_PREFIX_PATH}/attendance`,
// 						title: 'Посещаемость',
// 						icon: TableOutlined,
// 						breadcrumb: true,
// 						role: ['superadmin', 'administrator', 'employee'],
// 				},
// 				{
// 						key: 'employees',
// 						path: `${APP_PREFIX_PATH}/employees`,
// 						title: 'Сотрудники',
// 						breadcrumb: true,
// 						role: ['superadmin', 'administrator'],
// 				},
// 				{
// 						key: 'logs',
// 						path: `${APP_PREFIX_PATH}/logs`,
// 						title: 'Логи',
// 						breadcrumb: true,
// 						role: ['superadmin', 'administrator'],
// 				},
// 				{
// 						key: 'guests',
// 						path: `${APP_PREFIX_PATH}/guests`,
// 						title: 'Настройки гостей',
// 						breadcrumb: true,
// 						role: ['superadmin', 'administrator', 'employee'],
// 				},
// 				{
// 						key: 'transport-settings',
// 						path: `${APP_PREFIX_PATH}/transport-settings`,
// 						title: 'Транспорт',
// 						breadcrumb: true,
// 						role: ['superadmin', 'administrator'],
// 				},
// 				{
// 						key: 'cameras-settings',
// 						path: `${APP_PREFIX_PATH}/cameras-settings`,
// 						title: 'Камеры',
// 						breadcrumb: true,
// 						role: ['superadmin', 'administrator', 'employee'],
// 				},
// 				{
// 						key: 'global-settings',
// 						title: 'Глобальные настройки',
// 						path: `${APP_PREFIX_PATH}/global-settings`,
// 						breadcrumb: true,
// 						role: ['superadmin'],
// 				},
// 		],
// },
]

export default navigationConfig
